name: SonarQube

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-8-core]
        node: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm test:coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info

  sonarqube:
    name: Code check
    runs-on: ${{ matrix.os }}
    needs: [tests]
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
